### ISSUE TITLE
AIX portability

### ISSUE THREAD

**Issue by emillon** [ANSSI-FR/caml-crush#17]
Hello,

First let me thank you for this piece of software, we've been using it at Cryptosense and it makes it super easy to talk to P11 DLLs across the network.

I guess this is more of a question than a bug report, but do you know how easy it is to port `pkcs11proxyd` to other Unixes? In particular I have AIX in mind. Since it works on freebsd it seems possible, but if you have more information I'm very interested.

Thanks!

**Comment by rb-anssi** [comment]
Hi Etienne,

It is good to know that Caml Crush can be useful, thanks for your feedback ;-)
While porting the C client libraries is quite easy, porting the Caml Crush daemon to other Unix flavors might not be so straight forward depending on the target. The main elements to have in mind when handling such a task are:
- Obviously, a strong requirement is that the Caml compiler and dependencies must be packaged or at least be able to be compiled on the target
- A somewhat weaker requirement would be to have a proper OCaml RPCgen as well as a proper IDLgen and Coccinelle semantic patcher on the target. This could be optional since you can generate RPC code as well as patched PKCS#11 IDL bindings on another host (beware however that you can't be sure that the code generated this way will be 100% compatible with the target platform ...).

Please do not hesitate to contribute to the project if you find time to bootstrap an AIX port! Also, do not hesitate do ask us more specific questions about RPCgen/IDL or other pkcs11proxyd details if we can be of any help.

**Comment by emillon** [comment]
OK, great! I will have a go at this. Of course if it is necessary to adapt some code, the changes will be contributed back. I'll keep you updated!
