### ISSUE TITLE
[TLS] Mutual Authentification "auth_required=required" return Openssl handshake error 5

### ISSUE THREAD

**Issue by Batouu** [ANSSI-FR/caml-crush#29]
I'm trying to perform mutual authentification with TLS/SSL support.
When i add the parameter to force peer client authentication in pkcs11proxyd.conf : 
peer_auth = "required"; 

I receive an openSSL error  : 
```
C:\Exploitation\Demo\pkcs11-tool --module C:\Client\Lib\lipb11clientssl.dll -l --pin 123 -O
OpenSSL *** Handshake error 5
OpenSSL Error
```
I'm on centOS 7.2 and i use the ocamlnet 4.1.2 version.

Without this option, i got the following messages from Wireshark : 
```
TLSv1.2  Client Hello (Client -> Server)
""       Server Hello (Server -> Client)
""       Certificate Server Key Exchange, Server Hello Done (Server -> Client)
""       Client Key Exchange, Change Cipher Spec, Ecnrypted Handshake Message (Client -> Server)
""       Change CipherSpec (Server-> Client)
""       Hello Request, Hello Request (Serveur -> Client)
""       Application Data (Client -> Server)
""       Application Data (Server -> Client)
...       ...
```
With "peer_auth = required" : 
```
TLSv1.2  Client Hello (Client -> Server)
""       Server Hello (Server > Client)
""       Certificate Server Key Exchange (Server -> Client)
""       Certificate RequestServer Hello Done (Server -> Client)
""       Certificate, Client Key Exchange, Certificate Verify, Change Cipher, Encrypted Message (Client -> Server)
""       Change Cipher Spec   (Server -> Client)
```  ( the capture ends here)

**Comment by rb-anssi** [comment]
Hi Batouu,

The observed error seems to be reated to an issue in Ocamlnet: the code in src/nettls-gnutls/nettls_gnutls.ml shows that when peer_auth is set to "required", the server enforces a check on the peer certificates (which is normal and succeeds) as well as a check on the peer name (i.e. a check that the peer name is the same as the one in the certificate). This last check is of interest when dealing with servers, but it makes little sense when considering clients: the peer name is left void in this case, and the check fails.

Please consider raising an issue (or better: asking for a pull request) on the Ocamlnet project page: from the Caml-Crush perspective, this is not a project related issue.

This issue seems to have been introduced when Ocamlnet has migrated from OpenSSL to GnuTLS SSL bindings (in version 4): if your requirement of a mutual authentication is urgent, you can still fall back to an older version of Ocamlnet and recompile Caml-Crush.

Regards,

**Comment by stephane-martin** [comment]
Réf: https://gitlab.camlcity.org/gerd/lib-ocamlnet3/issues/9

**Comment by rb-anssi** [comment]
Hi Stéphane,

Thanks for the issue on the Ocamlnet project. We have found a workaround for Caml-Crush in order to be able to perform a mutual authentication with "peer_auth=required" despite this issue (this workaround is however a kind of "dirty hack" and won't replace a proper patch of Ocamlnet if/when the problem is confirmed on their side).

We are currently preparing commits to handle this.

Regards,

**Comment by stephane-martin** [comment]
Thanks, that would be great. An additional difficulty is that we work with the camlcrush client on Windows...

**Comment by rb-anssi** [comment]
Stéphane,

The commits are still under review, but the pending pull requests https://github.com/calderonth/caml-crush/pulls should bring what you expect:

1) The workaround with Ocamlnet 'peer_auth=required'.
2) A first attempt of providing a mingw cross-compilation Makefile for the client library. Please beware of the linking dependencies (oncrpc and OpenSSL libraries compiled for win32).

Any feedbacks/comments/contributions are welcome.

Regards,

**Comment by gerdstolpmann** [comment]
HI,

I'm the author of Ocamlnet. Just to understand the issue better: so, the problem is that (a) there is a server, which (b) is configured to authenticate the client, and (c) the mistake is that the DNS name of the client is compared with the subject in the certificate? That's what I extracted from the foregoing without known Caml-Crush.

Gerd

**Comment by rb-anssi** [comment]
Hi Gerd,

First, thanks for your answer regarding this issue!

I confirm that your understanding is correct: the DNS name being empty, the check fails even though the certificates chain has been correctly verified.

We have circumvented this by overriding ~verify in Netplex_config.read_tls_config so that there is no more DNS check, but I feel that this is a 'dirty hack' in a situation that should be properly handled by the Ocamlnet server, or did I miss something?

Regards,

**Comment by gerdstolpmann** [comment]
Hi Ryad,

well, ~verify exists to be overridable, so I think it is a good workaround. I also consider the bad verification as an error in Ocamlnet - clients almost never have proper DNS names.

Gerd

**Comment by rb-anssi** [comment]
Hi Gerd,

Thanks for the confirmation and for your feedback on this: since you confirm it is a good workaround, we will stick with the ~verify trick for now!

Regards,

**Comment by stephane-martin** [comment]
Then it would be nice to commit the patch to the master branch of the official repo... Right now they are only available as PR on the calderonth/caml-crush repo. Thank you.

**Comment by stephane-martin** [comment]
Hello, does anyone still maintain this project ? It looks like the PR from the calderonth fork were never ingregrated in either repo ?

**Comment by calderonth** [comment]
Hello,

Yes the project is still maintained, conflicting priorities came in the way.

Reviewing and merging the outstanding PRs is on my to do list for November.

Cheers,

Thomas
